services:
  db:
    image: mysql:8.4   # Menggunakan MySQL versi 8
    container_name: mysql-service  # Menetapkan nama container untuk db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}
    volumes:
      - ${MYSQL_DATA_PATH}

volumes:
  mysql_data:
