version: '3.1'

services:
  db:
    image: mysql:8.0   # Menggunakan MySQL versi 8
    container_name: mysql-service  # Menetapkan nama container untuk db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpmyadmin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-service  # Menetapkan nama container untuk phpmyadmin
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql_data:
