version: '3.1'

services:
  mongodb:
    image: mongo:latest  # Menggunakan image MongoDB terbaru
    container_name: mongodb-service 
    restart: always 
    ports:
      - "27017:27017"  # Memetakan port MongoDB ke port host
    volumes:
      - mongo_data:/data/db  # Menggunakan volume untuk persistensi data
  
volumes:
  mongo_data:
